{
 "title": "Dashboard Banco de Dados DevOps",
 "tags": [ "Banco de Dados" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Node Status",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "Node {{instance}}" }
   ]
  },
  {
   "title": "Prometheus HTTP Requests",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "{{handler}} - {{job}}" }
   ]
  },
  {
   "title": "MariaDB Threads Connected",
   "type": "graph",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mariadb_threads_connected", "legendFormat": "Threads Connected" }
   ]
  },
  {
   "title": "MariaDB Queries",
   "type": "graph",
   "gridPos": { "x": 0, "y": 30, "w": 24, "h": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mariadb_queries", "legendFormat": "Queries" }
   ]
  }
 ]
}